angelleye/paypal-woocommerce

classes/lib/composer/ClassLoader.php
See the #468 issue.
Don't hesitate to put it in a differed milestone or branch.
=> Provide a ClassLoader enabled to use PSR-4 loading (close #468)

template/paypal-review-order.php
- Moved Terms checkbox inside Label to make them easier acessible on mobile + better looks
- If not Tersm checked page scroll up to error message
- Added Hook after Terms for allow add extra things
=> Terms changes

angelleye-includes/angelleye-utility.php
Total order to capture is calculated substracting discount and/or amount already refunded
=> Fix EC capture after discount or refund

paypal-for-woocommerce.php, readme.txt
resolve closing tag missing issue #859
=> resolve closing tag missing issue

angelleye-includes/express-checkout/class-wc-gateway-paypal-express-helper-angelleye.php
=> Removed duplicate forward slash in asset path

angelleye-includes/express-checkout/class-wc-gateway-paypal-express-request-angelleye.php
=> fix error data is not written as order note correctly

angelleye-includes/angelleye-utility.php
Reverts angelleye/paypal-woocommerce#1360
=> Revert "Payflow: IP not being captured and forwarded to PayPal, PFW-484"

classes/lib/lib/Braintree.php, classes/wc-gateway-braintree-angelleye.php, paypal-for-woocommerce.php
This pull request resolves the Fatal Error that is thrown when the PHP version is less than the required version. Also, it shows notices if some of the required extension is not available.
=> Fixes Braintree PHP Version check exception - PFW-603

paypal-for-woocommerce.php
Removes the Version string from HTML header, #1457
=> Removes the Version string from HTML header, PFW-694

classes/wc-gateway-paypal-credit-cards-rest-angelleye.php
Added the deprecation notice message for the PayPal Credit Card Rest API, PFW-685, fixes #1488
=> Added the deprecation notice message, PFW-685

ppcp-gateway/class-angelleye-paypal-ppcp-pay-later-messaging.php
…ith Woo tax settings, PFW-1027
=> PPCP - Pay Later Messaging - Use including tax price : PFW-1027

angelleye-includes/express-checkout/class-wc-gateway-paypal-express-request-angelleye.php
This fix addresses the payment mode detection issue in the functions hooked to the angelleye_express_checkout_order_data action
=> PATCH - Fixed the sandbox flag update issue before the hook call

ppcp-gateway/class-angelleye-paypal-ppcp-payment.php, ppcp-gateway/class-angelleye-paypal-ppcp-smart-button.php, ppcp-gateway/js/wc-gateway-ppcp-angelleye-public.js
- Fixed the automatic ideal payment order capture/complete issue leading to refund
- Display iDeal payment method to users for Netherland shops without logging in
=> PFW-1066 - Fixed the automatic ideal payment order capture/complete issue leading to refund

paypal-for-woocommerce.php, ppcp-gateway/class-angelleye-paypal-ppcp-admin-action.php, ppcp-gateway/class-angelleye-paypal-ppcp-seller-onboarding.php, ppcp-gateway/class-wc-gateway-ppcp-angelleye.php
=> PFW-1499 - Optimised the seller onboarding status API call to fix the website load issue

ppcp-gateway/angelleye-paypal-ppcp-common-functions.php, ppcp-gateway/class-angelleye-paypal-ppcp-pay-later-messaging.php, ppcp-gateway/class-angelleye-paypal-ppcp-smart-button.php, ppcp-gateway/js/pay-later-messaging.js, ppcp-gateway/js/wc-angelleye-common-functions.js, ppcp-gateway/js/wc-gateway-ppcp-angelleye-apple-pay.js, ppcp-gateway/js/wc-gateway-ppcp-angelleye-public.js
Multi-Currency country code support added for plugins like Aelia Currency Convertors
=> PFW-1631 - Multi-Currency country code support added for plugins

ppcp-gateway/class-angelleye-paypal-ppcp-payment.php, ppcp-gateway/class-angelleye-paypal-ppcp-smart-button.php, ppcp-gateway/js/wc-angelleye-common-functions.js
- Helps with return user checkout experience.
=> PFW-1643 - Optimized the ID and Client token API calls

ppcp-gateway/angelleye-paypal-ppcp-common-functions.php, ppcp-gateway/class-angelleye-paypal-ppcp-front-action.php, ppcp-gateway/class-angelleye-paypal-ppcp-smart-button.php
- Fixes company name copy issue with shipping address fields
- Honors ship_to_different_address flag on the checkout page
=> PFW-1644 - Fixed the shipping address override issue on checkout page

ppcp-gateway/class-angelleye-paypal-ppcp-smart-button.php
https://angelleye.atlassian.net/browse/PFW-1757
https://angelleye.atlassian.net/browse/PFW-1755
=> PFW-1755, Express Checkout section compatibility with CheckoutWC

ppcp-gateway/class-wc-gateway-cc-angelleye.php
https://angelleye.atlassian.net/browse/PFW-1762
=> CVC field is missing on checkout page for subscriptions with trial period

ppcp-gateway/angelleye-paypal-ppcp-common-functions.php
bug fix found during WPML testing
=> PFW-1869 bug fix found during WPML testing

angelleye-includes/angelleye-utility.php, classes/wc-gateway-braintree-angelleye.php
=> PFW-1886, Encrypted values being passed into BT gateway settings request causing failure
